name = "ww"

[extra_sources]
"exec:go" = ["./extra/ww"]
"docker:go" = ["./extra/ww"]

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.14"
module_path = "github.com/wetware/lab"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/wetware/lab"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "canary"
instances = {min = 1, max = 1, default = 1}

[[testcases]]
name = "announce"
instances = { min = 2, max = 200, default = 5 }

# [[testcases]]
# # Test that heartbeat sequence numbers are monotonically increasing.  This is required
# # for the filter to work properly.
# name = "heartbeat"
# # Host routing can result in out-of-order delivery, so this testcase only supports one
# # instance
# instances = {min = 1, max = 1, default = 1}

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
